/**
 * @tripp-os/agent-bus — Trace Ledger Schemas
 *
 * Append-only Agent Bus trace event types.
 * Trace events are evidence only — they never authorize mutation.
 */
import { z } from "zod";
export declare const AgentBusTraceEventTypeSchema: z.ZodEnum<["packet_created", "packet_read", "packet_claimed", "result_written", "result_read", "schema_validation_failed", "packet_rejected", "packet_archived", "warden_review_started", "warden_verdict_recorded", "warden_stop_issued", "warden_stop_resolved", "subagent_spawned", "subagent_completed", "subagent_killed", "subagent_audited", "task_timeout", "tools_loaded", "tools_unloaded", "tool_timeout", "human_decision_recorded", "mutation_requested", "approvalgate_required", "mutation_applied", "validation_failed_later", "root_cause_linked", "approval_timeout"]>;
export type AgentBusTraceEventType = z.infer<typeof AgentBusTraceEventTypeSchema>;
export declare const AgentBusTraceSeveritySchema: z.ZodEnum<["debug", "info", "warning", "error", "critical"]>;
export type AgentBusTraceSeverity = z.infer<typeof AgentBusTraceSeveritySchema>;
export declare const AgentBusTraceActorTypeSchema: z.ZodEnum<["cli", "openclaw_tripp", "hermes_cyony", "openclaw_echo", "operator", "approvalgate", "system", "unknown"]>;
export type AgentBusTraceActorType = z.infer<typeof AgentBusTraceActorTypeSchema>;
export declare const AgentBusTraceEventSchema: z.ZodObject<{
    schemaVersion: z.ZodDefault<z.ZodString>;
    eventId: z.ZodString;
    eventType: z.ZodEnum<["packet_created", "packet_read", "packet_claimed", "result_written", "result_read", "schema_validation_failed", "packet_rejected", "packet_archived", "warden_review_started", "warden_verdict_recorded", "warden_stop_issued", "warden_stop_resolved", "subagent_spawned", "subagent_completed", "subagent_killed", "subagent_audited", "task_timeout", "tools_loaded", "tools_unloaded", "tool_timeout", "human_decision_recorded", "mutation_requested", "approvalgate_required", "mutation_applied", "validation_failed_later", "root_cause_linked", "approval_timeout"]>;
    severity: z.ZodDefault<z.ZodEnum<["debug", "info", "warning", "error", "critical"]>>;
    createdAt: z.ZodString;
    actorType: z.ZodEnum<["cli", "openclaw_tripp", "hermes_cyony", "openclaw_echo", "operator", "approvalgate", "system", "unknown"]>;
    actorId: z.ZodOptional<z.ZodString>;
    runId: z.ZodOptional<z.ZodString>;
    parentRunId: z.ZodOptional<z.ZodString>;
    packetId: z.ZodOptional<z.ZodString>;
    resultId: z.ZodOptional<z.ZodString>;
    reviewId: z.ZodOptional<z.ZodString>;
    parentEventId: z.ZodOptional<z.ZodString>;
    rootCauseEventId: z.ZodOptional<z.ZodString>;
    agentRole: z.ZodOptional<z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>>;
    parentAgentRole: z.ZodOptional<z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>>;
    subagentId: z.ZodOptional<z.ZodString>;
    subagentRole: z.ZodOptional<z.ZodString>;
    toolNames: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    sourcePath: z.ZodOptional<z.ZodString>;
    targetPath: z.ZodOptional<z.ZodString>;
    summary: z.ZodString;
    details: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    schemaVersion: string;
    eventId: string;
    eventType: "packet_created" | "packet_read" | "packet_claimed" | "result_written" | "result_read" | "schema_validation_failed" | "packet_rejected" | "packet_archived" | "warden_review_started" | "warden_verdict_recorded" | "warden_stop_issued" | "warden_stop_resolved" | "subagent_spawned" | "subagent_completed" | "subagent_killed" | "subagent_audited" | "task_timeout" | "tools_loaded" | "tools_unloaded" | "tool_timeout" | "human_decision_recorded" | "mutation_requested" | "approvalgate_required" | "mutation_applied" | "validation_failed_later" | "root_cause_linked" | "approval_timeout";
    severity: "debug" | "info" | "warning" | "error" | "critical";
    createdAt: string;
    actorType: "cli" | "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "operator" | "approvalgate" | "system" | "unknown";
    toolNames: string[];
    summary: string;
    tags: string[];
    actorId?: string | undefined;
    runId?: string | undefined;
    parentRunId?: string | undefined;
    packetId?: string | undefined;
    resultId?: string | undefined;
    reviewId?: string | undefined;
    parentEventId?: string | undefined;
    rootCauseEventId?: string | undefined;
    agentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    parentAgentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    subagentId?: string | undefined;
    subagentRole?: string | undefined;
    sourcePath?: string | undefined;
    targetPath?: string | undefined;
    details?: Record<string, unknown> | undefined;
}, {
    eventId: string;
    eventType: "packet_created" | "packet_read" | "packet_claimed" | "result_written" | "result_read" | "schema_validation_failed" | "packet_rejected" | "packet_archived" | "warden_review_started" | "warden_verdict_recorded" | "warden_stop_issued" | "warden_stop_resolved" | "subagent_spawned" | "subagent_completed" | "subagent_killed" | "subagent_audited" | "task_timeout" | "tools_loaded" | "tools_unloaded" | "tool_timeout" | "human_decision_recorded" | "mutation_requested" | "approvalgate_required" | "mutation_applied" | "validation_failed_later" | "root_cause_linked" | "approval_timeout";
    createdAt: string;
    actorType: "cli" | "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "operator" | "approvalgate" | "system" | "unknown";
    summary: string;
    schemaVersion?: string | undefined;
    severity?: "debug" | "info" | "warning" | "error" | "critical" | undefined;
    actorId?: string | undefined;
    runId?: string | undefined;
    parentRunId?: string | undefined;
    packetId?: string | undefined;
    resultId?: string | undefined;
    reviewId?: string | undefined;
    parentEventId?: string | undefined;
    rootCauseEventId?: string | undefined;
    agentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    parentAgentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    subagentId?: string | undefined;
    subagentRole?: string | undefined;
    toolNames?: string[] | undefined;
    sourcePath?: string | undefined;
    targetPath?: string | undefined;
    details?: Record<string, unknown> | undefined;
    tags?: string[] | undefined;
}>;
export type AgentBusTraceEvent = z.infer<typeof AgentBusTraceEventSchema>;
/** Validated trace event schema with runtime checks */
export declare const ValidatedTraceEventSchema: z.ZodEffects<z.ZodObject<{
    schemaVersion: z.ZodDefault<z.ZodString>;
    eventId: z.ZodString;
    eventType: z.ZodEnum<["packet_created", "packet_read", "packet_claimed", "result_written", "result_read", "schema_validation_failed", "packet_rejected", "packet_archived", "warden_review_started", "warden_verdict_recorded", "warden_stop_issued", "warden_stop_resolved", "subagent_spawned", "subagent_completed", "subagent_killed", "subagent_audited", "task_timeout", "tools_loaded", "tools_unloaded", "tool_timeout", "human_decision_recorded", "mutation_requested", "approvalgate_required", "mutation_applied", "validation_failed_later", "root_cause_linked", "approval_timeout"]>;
    severity: z.ZodDefault<z.ZodEnum<["debug", "info", "warning", "error", "critical"]>>;
    createdAt: z.ZodString;
    actorType: z.ZodEnum<["cli", "openclaw_tripp", "hermes_cyony", "openclaw_echo", "operator", "approvalgate", "system", "unknown"]>;
    actorId: z.ZodOptional<z.ZodString>;
    runId: z.ZodOptional<z.ZodString>;
    parentRunId: z.ZodOptional<z.ZodString>;
    packetId: z.ZodOptional<z.ZodString>;
    resultId: z.ZodOptional<z.ZodString>;
    reviewId: z.ZodOptional<z.ZodString>;
    parentEventId: z.ZodOptional<z.ZodString>;
    rootCauseEventId: z.ZodOptional<z.ZodString>;
    agentRole: z.ZodOptional<z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>>;
    parentAgentRole: z.ZodOptional<z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>>;
    subagentId: z.ZodOptional<z.ZodString>;
    subagentRole: z.ZodOptional<z.ZodString>;
    toolNames: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    sourcePath: z.ZodOptional<z.ZodString>;
    targetPath: z.ZodOptional<z.ZodString>;
    summary: z.ZodString;
    details: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    schemaVersion: string;
    eventId: string;
    eventType: "packet_created" | "packet_read" | "packet_claimed" | "result_written" | "result_read" | "schema_validation_failed" | "packet_rejected" | "packet_archived" | "warden_review_started" | "warden_verdict_recorded" | "warden_stop_issued" | "warden_stop_resolved" | "subagent_spawned" | "subagent_completed" | "subagent_killed" | "subagent_audited" | "task_timeout" | "tools_loaded" | "tools_unloaded" | "tool_timeout" | "human_decision_recorded" | "mutation_requested" | "approvalgate_required" | "mutation_applied" | "validation_failed_later" | "root_cause_linked" | "approval_timeout";
    severity: "debug" | "info" | "warning" | "error" | "critical";
    createdAt: string;
    actorType: "cli" | "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "operator" | "approvalgate" | "system" | "unknown";
    toolNames: string[];
    summary: string;
    tags: string[];
    actorId?: string | undefined;
    runId?: string | undefined;
    parentRunId?: string | undefined;
    packetId?: string | undefined;
    resultId?: string | undefined;
    reviewId?: string | undefined;
    parentEventId?: string | undefined;
    rootCauseEventId?: string | undefined;
    agentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    parentAgentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    subagentId?: string | undefined;
    subagentRole?: string | undefined;
    sourcePath?: string | undefined;
    targetPath?: string | undefined;
    details?: Record<string, unknown> | undefined;
}, {
    eventId: string;
    eventType: "packet_created" | "packet_read" | "packet_claimed" | "result_written" | "result_read" | "schema_validation_failed" | "packet_rejected" | "packet_archived" | "warden_review_started" | "warden_verdict_recorded" | "warden_stop_issued" | "warden_stop_resolved" | "subagent_spawned" | "subagent_completed" | "subagent_killed" | "subagent_audited" | "task_timeout" | "tools_loaded" | "tools_unloaded" | "tool_timeout" | "human_decision_recorded" | "mutation_requested" | "approvalgate_required" | "mutation_applied" | "validation_failed_later" | "root_cause_linked" | "approval_timeout";
    createdAt: string;
    actorType: "cli" | "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "operator" | "approvalgate" | "system" | "unknown";
    summary: string;
    schemaVersion?: string | undefined;
    severity?: "debug" | "info" | "warning" | "error" | "critical" | undefined;
    actorId?: string | undefined;
    runId?: string | undefined;
    parentRunId?: string | undefined;
    packetId?: string | undefined;
    resultId?: string | undefined;
    reviewId?: string | undefined;
    parentEventId?: string | undefined;
    rootCauseEventId?: string | undefined;
    agentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    parentAgentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    subagentId?: string | undefined;
    subagentRole?: string | undefined;
    toolNames?: string[] | undefined;
    sourcePath?: string | undefined;
    targetPath?: string | undefined;
    details?: Record<string, unknown> | undefined;
    tags?: string[] | undefined;
}>, {
    schemaVersion: string;
    eventId: string;
    eventType: "packet_created" | "packet_read" | "packet_claimed" | "result_written" | "result_read" | "schema_validation_failed" | "packet_rejected" | "packet_archived" | "warden_review_started" | "warden_verdict_recorded" | "warden_stop_issued" | "warden_stop_resolved" | "subagent_spawned" | "subagent_completed" | "subagent_killed" | "subagent_audited" | "task_timeout" | "tools_loaded" | "tools_unloaded" | "tool_timeout" | "human_decision_recorded" | "mutation_requested" | "approvalgate_required" | "mutation_applied" | "validation_failed_later" | "root_cause_linked" | "approval_timeout";
    severity: "debug" | "info" | "warning" | "error" | "critical";
    createdAt: string;
    actorType: "cli" | "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "operator" | "approvalgate" | "system" | "unknown";
    toolNames: string[];
    summary: string;
    tags: string[];
    actorId?: string | undefined;
    runId?: string | undefined;
    parentRunId?: string | undefined;
    packetId?: string | undefined;
    resultId?: string | undefined;
    reviewId?: string | undefined;
    parentEventId?: string | undefined;
    rootCauseEventId?: string | undefined;
    agentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    parentAgentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    subagentId?: string | undefined;
    subagentRole?: string | undefined;
    sourcePath?: string | undefined;
    targetPath?: string | undefined;
    details?: Record<string, unknown> | undefined;
}, {
    eventId: string;
    eventType: "packet_created" | "packet_read" | "packet_claimed" | "result_written" | "result_read" | "schema_validation_failed" | "packet_rejected" | "packet_archived" | "warden_review_started" | "warden_verdict_recorded" | "warden_stop_issued" | "warden_stop_resolved" | "subagent_spawned" | "subagent_completed" | "subagent_killed" | "subagent_audited" | "task_timeout" | "tools_loaded" | "tools_unloaded" | "tool_timeout" | "human_decision_recorded" | "mutation_requested" | "approvalgate_required" | "mutation_applied" | "validation_failed_later" | "root_cause_linked" | "approval_timeout";
    createdAt: string;
    actorType: "cli" | "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "operator" | "approvalgate" | "system" | "unknown";
    summary: string;
    schemaVersion?: string | undefined;
    severity?: "debug" | "info" | "warning" | "error" | "critical" | undefined;
    actorId?: string | undefined;
    runId?: string | undefined;
    parentRunId?: string | undefined;
    packetId?: string | undefined;
    resultId?: string | undefined;
    reviewId?: string | undefined;
    parentEventId?: string | undefined;
    rootCauseEventId?: string | undefined;
    agentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    parentAgentRole?: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo" | undefined;
    subagentId?: string | undefined;
    subagentRole?: string | undefined;
    toolNames?: string[] | undefined;
    sourcePath?: string | undefined;
    targetPath?: string | undefined;
    details?: Record<string, unknown> | undefined;
    tags?: string[] | undefined;
}>;
export declare const TraceLedgerValidationResultSchema: z.ZodObject<{
    totalLines: z.ZodNumber;
    validEvents: z.ZodNumber;
    malformedLines: z.ZodNumber;
    malformedLineNumbers: z.ZodArray<z.ZodNumber, "many">;
    ledgerPath: z.ZodString;
    isValid: z.ZodBoolean;
}, "strip", z.ZodTypeAny, {
    totalLines: number;
    validEvents: number;
    malformedLines: number;
    malformedLineNumbers: number[];
    ledgerPath: string;
    isValid: boolean;
}, {
    totalLines: number;
    validEvents: number;
    malformedLines: number;
    malformedLineNumbers: number[];
    ledgerPath: string;
    isValid: boolean;
}>;
export type TraceLedgerValidationResult = z.infer<typeof TraceLedgerValidationResultSchema>;
//# sourceMappingURL=traceSchemas.d.ts.map