/**
 * @tripp-os/agent-bus — Transport Schemas
 *
 * Bounded transport abstraction for routing packets to external workers.
 * All transports are fake/manual by default. Live/cloud is opt-in only.
 */
import { z } from "zod";
export declare const ExternalAgentTransportKindSchema: z.ZodEnum<["manual_file", "fake_agent", "local_process_experimental", "cloud_http_experimental"]>;
export type ExternalAgentTransportKind = z.infer<typeof ExternalAgentTransportKindSchema>;
export declare const ExternalAgentTransportModeSchema: z.ZodEnum<["disabled", "dry_run", "fake", "manual", "experimental_live"]>;
export type ExternalAgentTransportMode = z.infer<typeof ExternalAgentTransportModeSchema>;
export declare const ExternalAgentTransportConfigSchema: z.ZodObject<{
    transportId: z.ZodString;
    name: z.ZodString;
    kind: z.ZodEnum<["manual_file", "fake_agent", "local_process_experimental", "cloud_http_experimental"]>;
    mode: z.ZodEnum<["disabled", "dry_run", "fake", "manual", "experimental_live"]>;
    agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
    enabled: z.ZodDefault<z.ZodBoolean>;
    allowNetwork: z.ZodDefault<z.ZodBoolean>;
    allowSecrets: z.ZodDefault<z.ZodBoolean>;
    allowRepoAccess: z.ZodDefault<z.ZodBoolean>;
    allowDirectMutation: z.ZodDefault<z.ZodBoolean>;
    requireEchoReview: z.ZodDefault<z.ZodBoolean>;
    requireApprovalGate: z.ZodDefault<z.ZodBoolean>;
    timeoutSeconds: z.ZodDefault<z.ZodNumber>;
    maxContextTokens: z.ZodDefault<z.ZodNumber>;
    endpoint: z.ZodOptional<z.ZodString>;
    command: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    allowNetwork: boolean;
    allowSecrets: boolean;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    name: string;
    kind: "local_process_experimental" | "cloud_http_experimental" | "manual_file" | "fake_agent";
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    enabled: boolean;
    allowRepoAccess: boolean;
    allowDirectMutation: boolean;
    requireEchoReview: boolean;
    requireApprovalGate: boolean;
    timeoutSeconds: number;
    maxContextTokens: number;
    notes?: string | undefined;
    endpoint?: string | undefined;
    command?: string | undefined;
}, {
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    name: string;
    kind: "local_process_experimental" | "cloud_http_experimental" | "manual_file" | "fake_agent";
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    allowNetwork?: boolean | undefined;
    allowSecrets?: boolean | undefined;
    notes?: string | undefined;
    enabled?: boolean | undefined;
    allowRepoAccess?: boolean | undefined;
    allowDirectMutation?: boolean | undefined;
    requireEchoReview?: boolean | undefined;
    requireApprovalGate?: boolean | undefined;
    timeoutSeconds?: number | undefined;
    maxContextTokens?: number | undefined;
    endpoint?: string | undefined;
    command?: string | undefined;
}>;
export type ExternalAgentTransportConfig = z.infer<typeof ExternalAgentTransportConfigSchema>;
export declare const ValidatedTransportConfigSchema: z.ZodEffects<z.ZodObject<{
    transportId: z.ZodString;
    name: z.ZodString;
    kind: z.ZodEnum<["manual_file", "fake_agent", "local_process_experimental", "cloud_http_experimental"]>;
    mode: z.ZodEnum<["disabled", "dry_run", "fake", "manual", "experimental_live"]>;
    agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
    enabled: z.ZodDefault<z.ZodBoolean>;
    allowNetwork: z.ZodDefault<z.ZodBoolean>;
    allowSecrets: z.ZodDefault<z.ZodBoolean>;
    allowRepoAccess: z.ZodDefault<z.ZodBoolean>;
    allowDirectMutation: z.ZodDefault<z.ZodBoolean>;
    requireEchoReview: z.ZodDefault<z.ZodBoolean>;
    requireApprovalGate: z.ZodDefault<z.ZodBoolean>;
    timeoutSeconds: z.ZodDefault<z.ZodNumber>;
    maxContextTokens: z.ZodDefault<z.ZodNumber>;
    endpoint: z.ZodOptional<z.ZodString>;
    command: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    allowNetwork: boolean;
    allowSecrets: boolean;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    name: string;
    kind: "local_process_experimental" | "cloud_http_experimental" | "manual_file" | "fake_agent";
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    enabled: boolean;
    allowRepoAccess: boolean;
    allowDirectMutation: boolean;
    requireEchoReview: boolean;
    requireApprovalGate: boolean;
    timeoutSeconds: number;
    maxContextTokens: number;
    notes?: string | undefined;
    endpoint?: string | undefined;
    command?: string | undefined;
}, {
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    name: string;
    kind: "local_process_experimental" | "cloud_http_experimental" | "manual_file" | "fake_agent";
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    allowNetwork?: boolean | undefined;
    allowSecrets?: boolean | undefined;
    notes?: string | undefined;
    enabled?: boolean | undefined;
    allowRepoAccess?: boolean | undefined;
    allowDirectMutation?: boolean | undefined;
    requireEchoReview?: boolean | undefined;
    requireApprovalGate?: boolean | undefined;
    timeoutSeconds?: number | undefined;
    maxContextTokens?: number | undefined;
    endpoint?: string | undefined;
    command?: string | undefined;
}>, {
    allowNetwork: boolean;
    allowSecrets: boolean;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    name: string;
    kind: "local_process_experimental" | "cloud_http_experimental" | "manual_file" | "fake_agent";
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    enabled: boolean;
    allowRepoAccess: boolean;
    allowDirectMutation: boolean;
    requireEchoReview: boolean;
    requireApprovalGate: boolean;
    timeoutSeconds: number;
    maxContextTokens: number;
    notes?: string | undefined;
    endpoint?: string | undefined;
    command?: string | undefined;
}, {
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    name: string;
    kind: "local_process_experimental" | "cloud_http_experimental" | "manual_file" | "fake_agent";
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    allowNetwork?: boolean | undefined;
    allowSecrets?: boolean | undefined;
    notes?: string | undefined;
    enabled?: boolean | undefined;
    allowRepoAccess?: boolean | undefined;
    allowDirectMutation?: boolean | undefined;
    requireEchoReview?: boolean | undefined;
    requireApprovalGate?: boolean | undefined;
    timeoutSeconds?: number | undefined;
    maxContextTokens?: number | undefined;
    endpoint?: string | undefined;
    command?: string | undefined;
}>;
export declare const ExternalAgentDispatchRequestSchema: z.ZodEffects<z.ZodObject<{
    dispatchId: z.ZodString;
    packetId: z.ZodString;
    runId: z.ZodString;
    agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
    transportId: z.ZodString;
    mode: z.ZodEnum<["disabled", "dry_run", "fake", "manual", "experimental_live"]>;
    taskPacket: z.ZodObject<{
        schemaVersion: z.ZodDefault<z.ZodString>;
        packetId: z.ZodString;
        runId: z.ZodString;
        parentRunId: z.ZodOptional<z.ZodString>;
        createdAt: z.ZodString;
        createdBy: z.ZodString;
        agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
        trustZone: z.ZodEnum<["cloud_controlled_reasoning", "cloud_sandbox_proposal", "local_audit_warden", "human_approval"]>;
        taskType: z.ZodEnum<["plan", "review", "audit", "prototype", "proposal", "implementation_proposal", "warden_review", "swarm_decomposition", "report_review", "drift_check"]>;
        title: z.ZodString;
        objective: z.ZodString;
        scope: z.ZodString;
        allowedPaths: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        deniedPaths: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        toolPolicy: z.ZodDefault<z.ZodObject<{
            allowShell: z.ZodDefault<z.ZodBoolean>;
            allowWrite: z.ZodDefault<z.ZodBoolean>;
            allowNetwork: z.ZodDefault<z.ZodBoolean>;
            allowSecrets: z.ZodDefault<z.ZodBoolean>;
            allowedTools: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            deniedTools: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            notes: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            allowShell: boolean;
            allowWrite: boolean;
            allowNetwork: boolean;
            allowSecrets: boolean;
            allowedTools: string[];
            deniedTools: string[];
            notes?: string | undefined;
        }, {
            allowShell?: boolean | undefined;
            allowWrite?: boolean | undefined;
            allowNetwork?: boolean | undefined;
            allowSecrets?: boolean | undefined;
            allowedTools?: string[] | undefined;
            deniedTools?: string[] | undefined;
            notes?: string | undefined;
        }>>;
        approvalPolicy: z.ZodDefault<z.ZodObject<{
            requiresHumanApproval: z.ZodDefault<z.ZodBoolean>;
            requiresApprovalGate: z.ZodDefault<z.ZodBoolean>;
            agentMayApprove: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, boolean | undefined>;
            echoReviewRequired: z.ZodDefault<z.ZodBoolean>;
            notes: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            requiresHumanApproval: boolean;
            requiresApprovalGate: boolean;
            agentMayApprove: boolean;
            echoReviewRequired: boolean;
            notes?: string | undefined;
        }, {
            notes?: string | undefined;
            requiresHumanApproval?: boolean | undefined;
            requiresApprovalGate?: boolean | undefined;
            agentMayApprove?: boolean | undefined;
            echoReviewRequired?: boolean | undefined;
        }>>;
        contextPolicy: z.ZodDefault<z.ZodObject<{
            contextBudgetTokens: z.ZodNumber;
            redactSecrets: z.ZodDefault<z.ZodBoolean>;
            includeRepoSummary: z.ZodDefault<z.ZodBoolean>;
            includeFileContents: z.ZodDefault<z.ZodBoolean>;
            allowedContextPaths: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            deniedContextPaths: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            notes: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            contextBudgetTokens: number;
            redactSecrets: boolean;
            includeRepoSummary: boolean;
            includeFileContents: boolean;
            allowedContextPaths: string[];
            deniedContextPaths: string[];
            notes?: string | undefined;
        }, {
            contextBudgetTokens: number;
            notes?: string | undefined;
            redactSecrets?: boolean | undefined;
            includeRepoSummary?: boolean | undefined;
            includeFileContents?: boolean | undefined;
            allowedContextPaths?: string[] | undefined;
            deniedContextPaths?: string[] | undefined;
        }>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        requiredOutputFormat: z.ZodDefault<z.ZodString>;
        reportRequired: z.ZodDefault<z.ZodBoolean>;
        status: z.ZodDefault<z.ZodEnum<["pending", "claimed", "completed", "rejected", "blocked", "malformed", "archived"]>>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        status: "pending" | "claimed" | "completed" | "rejected" | "blocked" | "malformed" | "archived";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        createdBy: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        taskType: "plan" | "review" | "audit" | "prototype" | "proposal" | "implementation_proposal" | "warden_review" | "swarm_decomposition" | "report_review" | "drift_check";
        title: string;
        objective: string;
        scope: string;
        allowedPaths: string[];
        deniedPaths: string[];
        toolPolicy: {
            allowShell: boolean;
            allowWrite: boolean;
            allowNetwork: boolean;
            allowSecrets: boolean;
            allowedTools: string[];
            deniedTools: string[];
            notes?: string | undefined;
        };
        approvalPolicy: {
            requiresHumanApproval: boolean;
            requiresApprovalGate: boolean;
            agentMayApprove: boolean;
            echoReviewRequired: boolean;
            notes?: string | undefined;
        };
        contextPolicy: {
            contextBudgetTokens: number;
            redactSecrets: boolean;
            includeRepoSummary: boolean;
            includeFileContents: boolean;
            allowedContextPaths: string[];
            deniedContextPaths: string[];
            notes?: string | undefined;
        };
        constraints: string[];
        requiredOutputFormat: string;
        reportRequired: boolean;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
    }, {
        packetId: string;
        runId: string;
        createdAt: string;
        createdBy: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        taskType: "plan" | "review" | "audit" | "prototype" | "proposal" | "implementation_proposal" | "warden_review" | "swarm_decomposition" | "report_review" | "drift_check";
        title: string;
        objective: string;
        scope: string;
        status?: "pending" | "claimed" | "completed" | "rejected" | "blocked" | "malformed" | "archived" | undefined;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        allowedPaths?: string[] | undefined;
        deniedPaths?: string[] | undefined;
        toolPolicy?: {
            allowShell?: boolean | undefined;
            allowWrite?: boolean | undefined;
            allowNetwork?: boolean | undefined;
            allowSecrets?: boolean | undefined;
            allowedTools?: string[] | undefined;
            deniedTools?: string[] | undefined;
            notes?: string | undefined;
        } | undefined;
        approvalPolicy?: {
            notes?: string | undefined;
            requiresHumanApproval?: boolean | undefined;
            requiresApprovalGate?: boolean | undefined;
            agentMayApprove?: boolean | undefined;
            echoReviewRequired?: boolean | undefined;
        } | undefined;
        contextPolicy?: {
            contextBudgetTokens: number;
            notes?: string | undefined;
            redactSecrets?: boolean | undefined;
            includeRepoSummary?: boolean | undefined;
            includeFileContents?: boolean | undefined;
            allowedContextPaths?: string[] | undefined;
            deniedContextPaths?: string[] | undefined;
        } | undefined;
        constraints?: string[] | undefined;
        requiredOutputFormat?: string | undefined;
        reportRequired?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
    }>;
    createdAt: z.ZodString;
    requestedBy: z.ZodDefault<z.ZodString>;
    dryRun: z.ZodDefault<z.ZodBoolean>;
    traceEnabled: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    taskPacket: {
        status: "pending" | "claimed" | "completed" | "rejected" | "blocked" | "malformed" | "archived";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        createdBy: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        taskType: "plan" | "review" | "audit" | "prototype" | "proposal" | "implementation_proposal" | "warden_review" | "swarm_decomposition" | "report_review" | "drift_check";
        title: string;
        objective: string;
        scope: string;
        allowedPaths: string[];
        deniedPaths: string[];
        toolPolicy: {
            allowShell: boolean;
            allowWrite: boolean;
            allowNetwork: boolean;
            allowSecrets: boolean;
            allowedTools: string[];
            deniedTools: string[];
            notes?: string | undefined;
        };
        approvalPolicy: {
            requiresHumanApproval: boolean;
            requiresApprovalGate: boolean;
            agentMayApprove: boolean;
            echoReviewRequired: boolean;
            notes?: string | undefined;
        };
        contextPolicy: {
            contextBudgetTokens: number;
            redactSecrets: boolean;
            includeRepoSummary: boolean;
            includeFileContents: boolean;
            allowedContextPaths: string[];
            deniedContextPaths: string[];
            notes?: string | undefined;
        };
        constraints: string[];
        requiredOutputFormat: string;
        reportRequired: boolean;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
    };
    requestedBy: string;
    dryRun: boolean;
    traceEnabled: boolean;
}, {
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    taskPacket: {
        packetId: string;
        runId: string;
        createdAt: string;
        createdBy: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        taskType: "plan" | "review" | "audit" | "prototype" | "proposal" | "implementation_proposal" | "warden_review" | "swarm_decomposition" | "report_review" | "drift_check";
        title: string;
        objective: string;
        scope: string;
        status?: "pending" | "claimed" | "completed" | "rejected" | "blocked" | "malformed" | "archived" | undefined;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        allowedPaths?: string[] | undefined;
        deniedPaths?: string[] | undefined;
        toolPolicy?: {
            allowShell?: boolean | undefined;
            allowWrite?: boolean | undefined;
            allowNetwork?: boolean | undefined;
            allowSecrets?: boolean | undefined;
            allowedTools?: string[] | undefined;
            deniedTools?: string[] | undefined;
            notes?: string | undefined;
        } | undefined;
        approvalPolicy?: {
            notes?: string | undefined;
            requiresHumanApproval?: boolean | undefined;
            requiresApprovalGate?: boolean | undefined;
            agentMayApprove?: boolean | undefined;
            echoReviewRequired?: boolean | undefined;
        } | undefined;
        contextPolicy?: {
            contextBudgetTokens: number;
            notes?: string | undefined;
            redactSecrets?: boolean | undefined;
            includeRepoSummary?: boolean | undefined;
            includeFileContents?: boolean | undefined;
            allowedContextPaths?: string[] | undefined;
            deniedContextPaths?: string[] | undefined;
        } | undefined;
        constraints?: string[] | undefined;
        requiredOutputFormat?: string | undefined;
        reportRequired?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
    };
    requestedBy?: string | undefined;
    dryRun?: boolean | undefined;
    traceEnabled?: boolean | undefined;
}>, {
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    taskPacket: {
        status: "pending" | "claimed" | "completed" | "rejected" | "blocked" | "malformed" | "archived";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        createdBy: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        taskType: "plan" | "review" | "audit" | "prototype" | "proposal" | "implementation_proposal" | "warden_review" | "swarm_decomposition" | "report_review" | "drift_check";
        title: string;
        objective: string;
        scope: string;
        allowedPaths: string[];
        deniedPaths: string[];
        toolPolicy: {
            allowShell: boolean;
            allowWrite: boolean;
            allowNetwork: boolean;
            allowSecrets: boolean;
            allowedTools: string[];
            deniedTools: string[];
            notes?: string | undefined;
        };
        approvalPolicy: {
            requiresHumanApproval: boolean;
            requiresApprovalGate: boolean;
            agentMayApprove: boolean;
            echoReviewRequired: boolean;
            notes?: string | undefined;
        };
        contextPolicy: {
            contextBudgetTokens: number;
            redactSecrets: boolean;
            includeRepoSummary: boolean;
            includeFileContents: boolean;
            allowedContextPaths: string[];
            deniedContextPaths: string[];
            notes?: string | undefined;
        };
        constraints: string[];
        requiredOutputFormat: string;
        reportRequired: boolean;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
    };
    requestedBy: string;
    dryRun: boolean;
    traceEnabled: boolean;
}, {
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    taskPacket: {
        packetId: string;
        runId: string;
        createdAt: string;
        createdBy: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        taskType: "plan" | "review" | "audit" | "prototype" | "proposal" | "implementation_proposal" | "warden_review" | "swarm_decomposition" | "report_review" | "drift_check";
        title: string;
        objective: string;
        scope: string;
        status?: "pending" | "claimed" | "completed" | "rejected" | "blocked" | "malformed" | "archived" | undefined;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        allowedPaths?: string[] | undefined;
        deniedPaths?: string[] | undefined;
        toolPolicy?: {
            allowShell?: boolean | undefined;
            allowWrite?: boolean | undefined;
            allowNetwork?: boolean | undefined;
            allowSecrets?: boolean | undefined;
            allowedTools?: string[] | undefined;
            deniedTools?: string[] | undefined;
            notes?: string | undefined;
        } | undefined;
        approvalPolicy?: {
            notes?: string | undefined;
            requiresHumanApproval?: boolean | undefined;
            requiresApprovalGate?: boolean | undefined;
            agentMayApprove?: boolean | undefined;
            echoReviewRequired?: boolean | undefined;
        } | undefined;
        contextPolicy?: {
            contextBudgetTokens: number;
            notes?: string | undefined;
            redactSecrets?: boolean | undefined;
            includeRepoSummary?: boolean | undefined;
            includeFileContents?: boolean | undefined;
            allowedContextPaths?: string[] | undefined;
            deniedContextPaths?: string[] | undefined;
        } | undefined;
        constraints?: string[] | undefined;
        requiredOutputFormat?: string | undefined;
        reportRequired?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
    };
    requestedBy?: string | undefined;
    dryRun?: boolean | undefined;
    traceEnabled?: boolean | undefined;
}>;
export type ExternalAgentDispatchRequest = z.infer<typeof ExternalAgentDispatchRequestSchema>;
export declare const ExternalAgentDispatchStatusSchema: z.ZodEnum<["skipped", "dry_run", "fake_completed", "manual_required", "completed", "failed", "blocked", "unsafe"]>;
export type ExternalAgentDispatchStatus = z.infer<typeof ExternalAgentDispatchStatusSchema>;
export declare const ExternalAgentDispatchResultSchema: z.ZodObject<{
    dispatchId: z.ZodString;
    packetId: z.ZodString;
    resultId: z.ZodOptional<z.ZodString>;
    runId: z.ZodString;
    agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
    transportId: z.ZodString;
    mode: z.ZodEnum<["disabled", "dry_run", "fake", "manual", "experimental_live"]>;
    status: z.ZodEnum<["skipped", "dry_run", "fake_completed", "manual_required", "completed", "failed", "blocked", "unsafe"]>;
    summary: z.ZodString;
    resultPacket: z.ZodOptional<z.ZodObject<{
        schemaVersion: z.ZodDefault<z.ZodString>;
        packetId: z.ZodString;
        resultId: z.ZodString;
        runId: z.ZodString;
        parentRunId: z.ZodOptional<z.ZodString>;
        createdAt: z.ZodString;
        agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
        trustZone: z.ZodEnum<["cloud_controlled_reasoning", "cloud_sandbox_proposal", "local_audit_warden", "human_approval"]>;
        status: z.ZodEnum<["success", "partial", "failed", "blocked", "rejected", "unsafe", "malformed"]>;
        summary: z.ZodString;
        assumptions: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        risks: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        proposedChanges: z.ZodDefault<z.ZodArray<z.ZodObject<{
            path: z.ZodString;
            changeType: z.ZodEnum<["create", "modify", "delete", "rename", "review_only"]>;
            summary: z.ZodString;
            patch: z.ZodOptional<z.ZodString>;
            risk: z.ZodOptional<z.ZodEnum<["low", "medium", "high"]>>;
            requiresApproval: z.ZodDefault<z.ZodBoolean>;
        }, "strip", z.ZodTypeAny, {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            requiresApproval: boolean;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
        }, {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
            requiresApproval?: boolean | undefined;
        }>, "many">>;
        filesReferenced: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        validationPerformed: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        requestedApprovals: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        nextRecommendedAction: z.ZodDefault<z.ZodString>;
        reportPath: z.ZodOptional<z.ZodString>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        assumptions: string[];
        risks: string[];
        proposedChanges: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            requiresApproval: boolean;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
        }[];
        filesReferenced: string[];
        validationPerformed: string[];
        requestedApprovals: string[];
        nextRecommendedAction: string;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        reportPath?: string | undefined;
    }, {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        assumptions?: string[] | undefined;
        risks?: string[] | undefined;
        proposedChanges?: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
            requiresApproval?: boolean | undefined;
        }[] | undefined;
        filesReferenced?: string[] | undefined;
        validationPerformed?: string[] | undefined;
        requestedApprovals?: string[] | undefined;
        nextRecommendedAction?: string | undefined;
        reportPath?: string | undefined;
    }>>;
    outboxPath: z.ZodOptional<z.ZodString>;
    traceEventIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    errors: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    createdAt: z.ZodString;
    completedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "completed" | "blocked" | "failed" | "unsafe" | "dry_run" | "skipped" | "fake_completed" | "manual_required";
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    summary: string;
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    traceEventIds: string[];
    errors: string[];
    resultId?: string | undefined;
    resultPacket?: {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        assumptions: string[];
        risks: string[];
        proposedChanges: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            requiresApproval: boolean;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
        }[];
        filesReferenced: string[];
        validationPerformed: string[];
        requestedApprovals: string[];
        nextRecommendedAction: string;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        reportPath?: string | undefined;
    } | undefined;
    outboxPath?: string | undefined;
    completedAt?: string | undefined;
}, {
    status: "completed" | "blocked" | "failed" | "unsafe" | "dry_run" | "skipped" | "fake_completed" | "manual_required";
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    summary: string;
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    resultId?: string | undefined;
    resultPacket?: {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        assumptions?: string[] | undefined;
        risks?: string[] | undefined;
        proposedChanges?: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
            requiresApproval?: boolean | undefined;
        }[] | undefined;
        filesReferenced?: string[] | undefined;
        validationPerformed?: string[] | undefined;
        requestedApprovals?: string[] | undefined;
        nextRecommendedAction?: string | undefined;
        reportPath?: string | undefined;
    } | undefined;
    outboxPath?: string | undefined;
    traceEventIds?: string[] | undefined;
    errors?: string[] | undefined;
    completedAt?: string | undefined;
}>;
export type ExternalAgentDispatchResult = z.infer<typeof ExternalAgentDispatchResultSchema>;
export declare const ValidatedDispatchResultSchema: z.ZodEffects<z.ZodObject<{
    dispatchId: z.ZodString;
    packetId: z.ZodString;
    resultId: z.ZodOptional<z.ZodString>;
    runId: z.ZodString;
    agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
    transportId: z.ZodString;
    mode: z.ZodEnum<["disabled", "dry_run", "fake", "manual", "experimental_live"]>;
    status: z.ZodEnum<["skipped", "dry_run", "fake_completed", "manual_required", "completed", "failed", "blocked", "unsafe"]>;
    summary: z.ZodString;
    resultPacket: z.ZodOptional<z.ZodObject<{
        schemaVersion: z.ZodDefault<z.ZodString>;
        packetId: z.ZodString;
        resultId: z.ZodString;
        runId: z.ZodString;
        parentRunId: z.ZodOptional<z.ZodString>;
        createdAt: z.ZodString;
        agentRole: z.ZodEnum<["openclaw_tripp", "hermes_cyony", "openclaw_echo", "hermes_echo"]>;
        trustZone: z.ZodEnum<["cloud_controlled_reasoning", "cloud_sandbox_proposal", "local_audit_warden", "human_approval"]>;
        status: z.ZodEnum<["success", "partial", "failed", "blocked", "rejected", "unsafe", "malformed"]>;
        summary: z.ZodString;
        assumptions: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        risks: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        proposedChanges: z.ZodDefault<z.ZodArray<z.ZodObject<{
            path: z.ZodString;
            changeType: z.ZodEnum<["create", "modify", "delete", "rename", "review_only"]>;
            summary: z.ZodString;
            patch: z.ZodOptional<z.ZodString>;
            risk: z.ZodOptional<z.ZodEnum<["low", "medium", "high"]>>;
            requiresApproval: z.ZodDefault<z.ZodBoolean>;
        }, "strip", z.ZodTypeAny, {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            requiresApproval: boolean;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
        }, {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
            requiresApproval?: boolean | undefined;
        }>, "many">>;
        filesReferenced: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        validationPerformed: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        requestedApprovals: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        nextRecommendedAction: z.ZodDefault<z.ZodString>;
        reportPath: z.ZodOptional<z.ZodString>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        assumptions: string[];
        risks: string[];
        proposedChanges: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            requiresApproval: boolean;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
        }[];
        filesReferenced: string[];
        validationPerformed: string[];
        requestedApprovals: string[];
        nextRecommendedAction: string;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        reportPath?: string | undefined;
    }, {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        assumptions?: string[] | undefined;
        risks?: string[] | undefined;
        proposedChanges?: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
            requiresApproval?: boolean | undefined;
        }[] | undefined;
        filesReferenced?: string[] | undefined;
        validationPerformed?: string[] | undefined;
        requestedApprovals?: string[] | undefined;
        nextRecommendedAction?: string | undefined;
        reportPath?: string | undefined;
    }>>;
    outboxPath: z.ZodOptional<z.ZodString>;
    traceEventIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    errors: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    createdAt: z.ZodString;
    completedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "completed" | "blocked" | "failed" | "unsafe" | "dry_run" | "skipped" | "fake_completed" | "manual_required";
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    summary: string;
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    traceEventIds: string[];
    errors: string[];
    resultId?: string | undefined;
    resultPacket?: {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        assumptions: string[];
        risks: string[];
        proposedChanges: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            requiresApproval: boolean;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
        }[];
        filesReferenced: string[];
        validationPerformed: string[];
        requestedApprovals: string[];
        nextRecommendedAction: string;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        reportPath?: string | undefined;
    } | undefined;
    outboxPath?: string | undefined;
    completedAt?: string | undefined;
}, {
    status: "completed" | "blocked" | "failed" | "unsafe" | "dry_run" | "skipped" | "fake_completed" | "manual_required";
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    summary: string;
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    resultId?: string | undefined;
    resultPacket?: {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        assumptions?: string[] | undefined;
        risks?: string[] | undefined;
        proposedChanges?: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
            requiresApproval?: boolean | undefined;
        }[] | undefined;
        filesReferenced?: string[] | undefined;
        validationPerformed?: string[] | undefined;
        requestedApprovals?: string[] | undefined;
        nextRecommendedAction?: string | undefined;
        reportPath?: string | undefined;
    } | undefined;
    outboxPath?: string | undefined;
    traceEventIds?: string[] | undefined;
    errors?: string[] | undefined;
    completedAt?: string | undefined;
}>, {
    status: "completed" | "blocked" | "failed" | "unsafe" | "dry_run" | "skipped" | "fake_completed" | "manual_required";
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    summary: string;
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    traceEventIds: string[];
    errors: string[];
    resultId?: string | undefined;
    resultPacket?: {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        schemaVersion: string;
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        assumptions: string[];
        risks: string[];
        proposedChanges: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            requiresApproval: boolean;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
        }[];
        filesReferenced: string[];
        validationPerformed: string[];
        requestedApprovals: string[];
        nextRecommendedAction: string;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        reportPath?: string | undefined;
    } | undefined;
    outboxPath?: string | undefined;
    completedAt?: string | undefined;
}, {
    status: "completed" | "blocked" | "failed" | "unsafe" | "dry_run" | "skipped" | "fake_completed" | "manual_required";
    packetId: string;
    runId: string;
    createdAt: string;
    agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
    summary: string;
    transportId: string;
    mode: "fake" | "manual" | "disabled" | "dry_run" | "experimental_live";
    dispatchId: string;
    resultId?: string | undefined;
    resultPacket?: {
        status: "rejected" | "blocked" | "malformed" | "success" | "partial" | "failed" | "unsafe";
        packetId: string;
        runId: string;
        createdAt: string;
        agentRole: "openclaw_tripp" | "hermes_cyony" | "openclaw_echo" | "hermes_echo";
        trustZone: "cloud_controlled_reasoning" | "cloud_sandbox_proposal" | "local_audit_warden" | "human_approval";
        summary: string;
        resultId: string;
        schemaVersion?: string | undefined;
        parentRunId?: string | undefined;
        metadata?: Record<string, unknown> | undefined;
        assumptions?: string[] | undefined;
        risks?: string[] | undefined;
        proposedChanges?: {
            path: string;
            changeType: "create" | "modify" | "delete" | "rename" | "review_only";
            summary: string;
            patch?: string | undefined;
            risk?: "low" | "medium" | "high" | undefined;
            requiresApproval?: boolean | undefined;
        }[] | undefined;
        filesReferenced?: string[] | undefined;
        validationPerformed?: string[] | undefined;
        requestedApprovals?: string[] | undefined;
        nextRecommendedAction?: string | undefined;
        reportPath?: string | undefined;
    } | undefined;
    outboxPath?: string | undefined;
    traceEventIds?: string[] | undefined;
    errors?: string[] | undefined;
    completedAt?: string | undefined;
}>;
//# sourceMappingURL=transportSchemas.d.ts.map